// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package repository

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const createApplication = `-- name: CreateApplication :one

INSERT INTO applications(id,name,slug,environment_id,created_at,updated_at)
VALUES ($1,$2,$3,$4,$5,$6) 
RETURNING id, name, slug, environment_id, created_at, updated_at
`

type CreateApplicationParams struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Slug          string    `json:"slug"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.EnvironmentID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplicationByID = `-- name: DeleteApplicationByID :exec

DELETE  FROM applications WHERE id=$1 AND environment_id=$2
`

type DeleteApplicationByIDParams struct {
	ID            uuid.UUID `json:"id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) DeleteApplicationByID(ctx context.Context, arg DeleteApplicationByIDParams) error {
	_, err := q.db.Exec(ctx, deleteApplicationByID, arg.ID, arg.EnvironmentID)
	return err
}

const getAllApplicationsByEnvironmentID = `-- name: GetAllApplicationsByEnvironmentID :many

SELECT id, name, slug, environment_id, created_at, updated_at FROM applications WHERE environment_id=$1
`

func (q *Queries) GetAllApplicationsByEnvironmentID(ctx context.Context, environmentID uuid.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, getAllApplicationsByEnvironmentID, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.EnvironmentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationByID = `-- name: GetApplicationByID :one

SELECT id, name, slug, environment_id, created_at, updated_at FROM applications WHERE id=$1  AND environment_id=$2
`

type GetApplicationByIDParams struct {
	ID            uuid.UUID `json:"id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) GetApplicationByID(ctx context.Context, arg GetApplicationByIDParams) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, arg.ID, arg.EnvironmentID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApplicationById = `-- name: UpdateApplicationById :one

UPDATE applications
SET
    name=$1 ,
    slug=$2 ,
    updated_at=NOW()
WHERE id=$3 AND environment_id=$4
RETURNING id, name, slug, environment_id, created_at, updated_at
`

type UpdateApplicationByIdParams struct {
	Name          string    `json:"name"`
	Slug          string    `json:"slug"`
	ID            uuid.UUID `json:"id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) UpdateApplicationById(ctx context.Context, arg UpdateApplicationByIdParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplicationById,
		arg.Name,
		arg.Slug,
		arg.ID,
		arg.EnvironmentID,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
