// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package repository

import (
	"context"
)

// iteratorForCreateDeliveries implements pgx.CopyFromSource.
type iteratorForCreateDeliveries struct {
	rows                 []CreateDeliveriesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateDeliveries) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateDeliveries) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].MessageID,
		r.rows[0].EndpointID,
		r.rows[0].MaxAttempts,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
	}, nil
}

func (r iteratorForCreateDeliveries) Err() error {
	return nil
}

func (q *Queries) CreateDeliveries(ctx context.Context, arg []CreateDeliveriesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"deliveries"}, []string{"id", "message_id", "endpoint_id", "max_attempts", "created_at", "updated_at"}, &iteratorForCreateDeliveries{rows: arg})
}
