// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package repository

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

type CreateDeliveriesParams struct {
	ID          uuid.UUID `json:"id"`
	MessageID   uuid.UUID `json:"message_id"`
	EndpointID  uuid.UUID `json:"endpoint_id"`
	MaxAttempts int32     `json:"max_attempts"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

const deleteDeliveryByID = `-- name: DeleteDeliveryByID :exec

DELETE FROM deliveries WHERE id = $1
`

func (q *Queries) DeleteDeliveryByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeliveryByID, id)
	return err
}

const getAllDeliveriesByMessageID = `-- name: GetAllDeliveriesByMessageID :many

SELECT id, message_id, endpoint_id, status, attempts, max_attempts, next_attempt_at, locked_until, last_attempted_at, response_status, response_body, created_at, updated_at FROM deliveries WHERE message_id = $1
`

func (q *Queries) GetAllDeliveriesByMessageID(ctx context.Context, messageID uuid.UUID) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, getAllDeliveriesByMessageID, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Delivery{}
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.EndpointID,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.LockedUntil,
			&i.LastAttemptedAt,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeliveryByID = `-- name: GetDeliveryByID :one

SELECT id, message_id, endpoint_id, status, attempts, max_attempts, next_attempt_at, locked_until, last_attempted_at, response_status, response_body, created_at, updated_at FROM deliveries WHERE id = $1
`

func (q *Queries) GetDeliveryByID(ctx context.Context, id uuid.UUID) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDeliveryByID, id)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.EndpointID,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.LastAttemptedAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
