// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endpoints.sql

package repository

import (
	"context"
	"encoding/json"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEndpoint = `-- name: CreateEndpoint :one

INSERT INTO endpoints (id, name, application_id, url, method, headers, query_params, event_types, signing_secret, is_active, timeout_ms, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, name, application_id, url, method, headers, query_params, event_types, signing_secret, is_active, timeout_ms, created_at, updated_at
`

type CreateEndpointParams struct {
	ID            uuid.UUID        `json:"id"`
	Name          string           `json:"name"`
	ApplicationID uuid.UUID        `json:"application_id"`
	Url           string           `json:"url"`
	Method        string           `json:"method"`
	Headers       *json.RawMessage `json:"headers"`
	QueryParams   *json.RawMessage `json:"query_params"`
	EventTypes    []string         `json:"event_types"`
	SigningSecret pgtype.Text      `json:"signing_secret"`
	IsActive      bool             `json:"is_active"`
	TimeoutMs     int32            `json:"timeout_ms"`
	CreatedAt     time.Time        `json:"created_at"`
	UpdatedAt     time.Time        `json:"updated_at"`
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, createEndpoint,
		arg.ID,
		arg.Name,
		arg.ApplicationID,
		arg.Url,
		arg.Method,
		arg.Headers,
		arg.QueryParams,
		arg.EventTypes,
		arg.SigningSecret,
		arg.IsActive,
		arg.TimeoutMs,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApplicationID,
		&i.Url,
		&i.Method,
		&i.Headers,
		&i.QueryParams,
		&i.EventTypes,
		&i.SigningSecret,
		&i.IsActive,
		&i.TimeoutMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEndpointByID = `-- name: DeleteEndpointByID :exec

DELETE FROM endpoints WHERE id = $1 AND application_id = $2
`

type DeleteEndpointByIDParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

func (q *Queries) DeleteEndpointByID(ctx context.Context, arg DeleteEndpointByIDParams) error {
	_, err := q.db.Exec(ctx, deleteEndpointByID, arg.ID, arg.ApplicationID)
	return err
}

const getAllEndpointsByApplicationID = `-- name: GetAllEndpointsByApplicationID :many

SELECT id, name, application_id, url, method, headers, query_params, event_types, signing_secret, is_active, timeout_ms, created_at, updated_at FROM endpoints WHERE application_id = $1
`

func (q *Queries) GetAllEndpointsByApplicationID(ctx context.Context, applicationID uuid.UUID) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, getAllEndpointsByApplicationID, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Endpoint{}
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ApplicationID,
			&i.Url,
			&i.Method,
			&i.Headers,
			&i.QueryParams,
			&i.EventTypes,
			&i.SigningSecret,
			&i.IsActive,
			&i.TimeoutMs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEndpointByID = `-- name: GetEndpointByID :one

SELECT id, name, application_id, url, method, headers, query_params, event_types, signing_secret, is_active, timeout_ms, created_at, updated_at FROM endpoints WHERE id = $1 AND application_id = $2
`

type GetEndpointByIDParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

func (q *Queries) GetEndpointByID(ctx context.Context, arg GetEndpointByIDParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointByID, arg.ID, arg.ApplicationID)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApplicationID,
		&i.Url,
		&i.Method,
		&i.Headers,
		&i.QueryParams,
		&i.EventTypes,
		&i.SigningSecret,
		&i.IsActive,
		&i.TimeoutMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEndpointByID = `-- name: UpdateEndpointByID :one

UPDATE endpoints
SET
    name = $1,
    url = $2,
    method = $3,
    headers = $4,
    query_params = $5,
    event_types = $6,
    signing_secret = $7,
    is_active = $8,
    timeout_ms = $9,
    updated_at = NOW()
WHERE id=$10 and application_id=$11
RETURNING id, name, application_id, url, method, headers, query_params, event_types, signing_secret, is_active, timeout_ms, created_at, updated_at
`

type UpdateEndpointByIDParams struct {
	Name          string           `json:"name"`
	Url           string           `json:"url"`
	Method        string           `json:"method"`
	Headers       *json.RawMessage `json:"headers"`
	QueryParams   *json.RawMessage `json:"query_params"`
	EventTypes    []string         `json:"event_types"`
	SigningSecret pgtype.Text      `json:"signing_secret"`
	IsActive      bool             `json:"is_active"`
	TimeoutMs     int32            `json:"timeout_ms"`
	ID            uuid.UUID        `json:"id"`
	ApplicationID uuid.UUID        `json:"application_id"`
}

func (q *Queries) UpdateEndpointByID(ctx context.Context, arg UpdateEndpointByIDParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, updateEndpointByID,
		arg.Name,
		arg.Url,
		arg.Method,
		arg.Headers,
		arg.QueryParams,
		arg.EventTypes,
		arg.SigningSecret,
		arg.IsActive,
		arg.TimeoutMs,
		arg.ID,
		arg.ApplicationID,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApplicationID,
		&i.Url,
		&i.Method,
		&i.Headers,
		&i.QueryParams,
		&i.EventTypes,
		&i.SigningSecret,
		&i.IsActive,
		&i.TimeoutMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEndpointStatus = `-- name: UpdateEndpointStatus :one

UPDATE endpoints
SET
    is_active = $1,
    updated_at = NOW()
WHERE id = $2 AND application_id = $3
RETURNING id, name, application_id, url, method, headers, query_params, event_types, signing_secret, is_active, timeout_ms, created_at, updated_at
`

type UpdateEndpointStatusParams struct {
	IsActive      bool      `json:"is_active"`
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

func (q *Queries) UpdateEndpointStatus(ctx context.Context, arg UpdateEndpointStatusParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, updateEndpointStatus, arg.IsActive, arg.ID, arg.ApplicationID)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApplicationID,
		&i.Url,
		&i.Method,
		&i.Headers,
		&i.QueryParams,
		&i.EventTypes,
		&i.SigningSecret,
		&i.IsActive,
		&i.TimeoutMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
