// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package repository

import (
	"context"
	"encoding/json"
	"time"

	uuid "github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one

INSERT INTO messages (id, application_id, event_type, payload, metadata, idempotency_key,created_at)
VALUES ($1, $2, $3, $4, $5, $6,$7)
RETURNING id, application_id, event_type, payload, metadata, idempotency_key, created_at
`

type CreateMessageParams struct {
	ID             uuid.UUID        `json:"id"`
	ApplicationID  uuid.UUID        `json:"application_id"`
	EventType      string           `json:"event_type"`
	Payload        json.RawMessage  `json:"payload"`
	Metadata       *json.RawMessage `json:"metadata"`
	IdempotencyKey string           `json:"idempotency_key"`
	CreatedAt      time.Time        `json:"created_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.ApplicationID,
		arg.EventType,
		arg.Payload,
		arg.Metadata,
		arg.IdempotencyKey,
		arg.CreatedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.EventType,
		&i.Payload,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMessageByID = `-- name: DeleteMessageByID :exec

DELETE FROM messages WHERE id = $1 AND application_id = $2
`

type DeleteMessageByIDParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

func (q *Queries) DeleteMessageByID(ctx context.Context, arg DeleteMessageByIDParams) error {
	_, err := q.db.Exec(ctx, deleteMessageByID, arg.ID, arg.ApplicationID)
	return err
}

const getAllMessagesByApplicationID = `-- name: GetAllMessagesByApplicationID :many

SELECT id, application_id, event_type, payload, metadata, idempotency_key, created_at FROM messages WHERE application_id = $1
`

func (q *Queries) GetAllMessagesByApplicationID(ctx context.Context, applicationID uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, getAllMessagesByApplicationID, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.EventType,
			&i.Payload,
			&i.Metadata,
			&i.IdempotencyKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageByID = `-- name: GetMessageByID :one

SELECT id, application_id, event_type, payload, metadata, idempotency_key, created_at FROM messages WHERE id = $1 AND application_id = $2
`

type GetMessageByIDParams struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

func (q *Queries) GetMessageByID(ctx context.Context, arg GetMessageByIDParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, arg.ID, arg.ApplicationID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.EventType,
		&i.Payload,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}
