// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DeliveryStatus string

const (
	DeliveryStatusPending      DeliveryStatus = "pending"
	DeliveryStatusDelivered    DeliveryStatus = "delivered"
	DeliveryStatusFailed       DeliveryStatus = "failed"
	DeliveryStatusDeadLettered DeliveryStatus = "dead_lettered"
)

func (e *DeliveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryStatus(s)
	case string:
		*e = DeliveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryStatus: %T", src)
	}
	return nil
}

type NullDeliveryStatus struct {
	DeliveryStatus DeliveryStatus `json:"delivery_status"`
	Valid          bool           `json:"valid"` // Valid is true if DeliveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryStatus), nil
}

type Application struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Slug          string    `json:"slug"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Delivery struct {
	ID              uuid.UUID      `json:"id"`
	MessageID       uuid.UUID      `json:"message_id"`
	EndpointID      uuid.UUID      `json:"endpoint_id"`
	Status          DeliveryStatus `json:"status"`
	Attempts        int32          `json:"attempts"`
	MaxAttempts     int32          `json:"max_attempts"`
	NextAttemptAt   time.Time      `json:"next_attempt_at"`
	LockedUntil     *time.Time     `json:"locked_until"`
	LastAttemptedAt *time.Time     `json:"last_attempted_at"`
	ResponseStatus  pgtype.Int4    `json:"response_status"`
	ResponseBody    pgtype.Text    `json:"response_body"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type Endpoint struct {
	ID            uuid.UUID        `json:"id"`
	Name          string           `json:"name"`
	ApplicationID uuid.UUID        `json:"application_id"`
	Url           string           `json:"url"`
	Method        string           `json:"method"`
	Headers       *json.RawMessage `json:"headers"`
	QueryParams   *json.RawMessage `json:"query_params"`
	EventTypes    []string         `json:"event_types"`
	SigningSecret pgtype.Text      `json:"signing_secret"`
	IsActive      bool             `json:"is_active"`
	TimeoutMs     int32            `json:"timeout_ms"`
	CreatedAt     time.Time        `json:"created_at"`
	UpdatedAt     time.Time        `json:"updated_at"`
}

type Environment struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Message struct {
	ID             uuid.UUID        `json:"id"`
	ApplicationID  uuid.UUID        `json:"application_id"`
	EventType      string           `json:"event_type"`
	Payload        json.RawMessage  `json:"payload"`
	Metadata       *json.RawMessage `json:"metadata"`
	IdempotencyKey string           `json:"idempotency_key"`
	CreatedAt      time.Time        `json:"created_at"`
}
