// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	uuid "github.com/google/uuid"
)

type Querier interface {
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error)
	CreateDeliveries(ctx context.Context, arg []CreateDeliveriesParams) (int64, error)
	CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error)
	CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	DeleteApplicationByID(ctx context.Context, arg DeleteApplicationByIDParams) error
	DeleteDeliveryByID(ctx context.Context, id uuid.UUID) error
	DeleteEndpointByID(ctx context.Context, arg DeleteEndpointByIDParams) error
	DeleteEnvironment(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	DeleteMessageByID(ctx context.Context, arg DeleteMessageByIDParams) error
	GetAllApplicationsByEnvironmentID(ctx context.Context, environmentID uuid.UUID) ([]Application, error)
	GetAllDeliveriesByMessageID(ctx context.Context, messageID uuid.UUID) ([]Delivery, error)
	GetAllEndpointsByApplicationID(ctx context.Context, applicationID uuid.UUID) ([]Endpoint, error)
	GetAllMessagesByApplicationID(ctx context.Context, applicationID uuid.UUID) ([]Message, error)
	GetApplicationByID(ctx context.Context, arg GetApplicationByIDParams) (Application, error)
	GetDeliveryByID(ctx context.Context, id uuid.UUID) (Delivery, error)
	GetEndpointByID(ctx context.Context, arg GetEndpointByIDParams) (Endpoint, error)
	GetEnvironmentById(ctx context.Context, id uuid.UUID) (Environment, error)
	GetMessageByID(ctx context.Context, arg GetMessageByIDParams) (Message, error)
	ListEnvironments(ctx context.Context) ([]Environment, error)
	UpdateApplicationById(ctx context.Context, arg UpdateApplicationByIdParams) (Application, error)
	UpdateEndpointByID(ctx context.Context, arg UpdateEndpointByIDParams) (Endpoint, error)
	UpdateEndpointStatus(ctx context.Context, arg UpdateEndpointStatusParams) (Endpoint, error)
}

var _ Querier = (*Queries)(nil)
