name: hookwave-server-setup 

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hookwave_db
    ports:
      - "5432:5432"
    volumes:
      - hookwave_postgres_data:/var/lib/postgresql/data

volumes:
  hookwave_postgres_data: